# TO be compatible with both arm64 architectures
FROM --platform=linux/arm64/v8 python:3.10-slim
# If want to tent the image in local environment, uncomment the next line (and comment the previous one)
#FROM --platform=linux/amd64/v8  python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install WiFi tools and network utilities
RUN apt-get update && apt-get install -y \
    wireless-tools \
    iw \
    wpasupplicant \
    dhcpcd5 \
    isc-dhcp-client \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy application files
COPY ./src /app
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8080

# Start application
CMD ["python", "app.py"]